Demyd
JavaRush-GNEW/M2-ISLAND-NEW pull request #5
Opened 2024-11-26 19:03 UTC by Demyd06

2024-11-26 19:04 UTC, Demyd06 commented
Добрий вечір! 
Став у ступор, не розумію , що робити далі

2024-12-06 17:09 UTC, Demyd06 commented
Добрий вечір! Зрозумів в чому проблема. При розробці лишив імплементацію Бгатопоточності на кінець і через це коли вся логіка працювала, і я під'єднав 3 потоки, вся логіка майже перестала працювати, працює Move and Hunt , можливо Розмноження.

2025-01-08 15:47 UTC, oleksandr-jr commented
Please remove .idea folder from this MR

2025-01-08 15:47 UTC, oleksandr-jr requested changes
Remove .idea

2025-02-05 16:36 UTC, merged